include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    constant_identifier_names: false
    avoid_classes_with_only_static_members: false
    prefer_relative_imports: true
